# Generated by Django 5.2.16 on 2026-07-27 15:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organization_organizationmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('individual_subscription', 'Individual subscription'), ('organization_quota', 'Organization quota'), ('sponsored_campaign', 'Sponsored campaign'), ('admin_grant', 'Admin grant')], max_length=32)),
                ('access_right', models.CharField(choices=[('read', 'Read'), ('download', 'Download'), ('offline', 'Offline')], max_length=16)),
                ('scope_type', models.CharField(choices=[('global', 'Global'), ('domain', 'Domain'), ('collection', 'Collection'), ('document', 'Document')], default='global', max_length=16)),
                ('scope_id', models.CharField(blank=True, max_length=128)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='accounts.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-starts_at', '-created_at'],
                'indexes': [models.Index(fields=['user', 'access_right', 'scope_type'], name='accounts_en_user_id_d13ec2_idx'), models.Index(fields=['organization', 'access_right', 'scope_type'], name='accounts_en_organiz_98923e_idx'), models.Index(fields=['starts_at', 'ends_at'], name='accounts_en_starts__48b466_idx')],
            },
        ),
    ]
