# Generated by Django 5.2.16 on 2026-08-21 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_entitlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='requires_identity_verification',
            field=models.BooleanField(default=True, help_text="Si vrai, seules les adhésions à l'identité vérifiée ouvrent l'accès (cas des universités partenaires offrant l'accès gratuit sur preuve). Mettre à faux pour une entreprise qui achète simplement des places."),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='proof_reference',
            field=models.CharField(blank=True, default='', help_text='Référence de la preuve stockée (clé de stockage, n° de dossier, domaine e-mail validé…). Jamais le fichier lui-même.', max_length=300),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='verification_method',
            field=models.CharField(blank=True, choices=[('student_card', 'Student card'), ('staff_id', 'Staff ID'), ('enrollment_certificate', 'Enrollment certificate'), ('email_domain', 'Institutional email domain'), ('manual', 'Manual admin decision'), ('other', 'Other')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='verification_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='unverified', max_length=16),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
