# Generated by Django 5.2.16 on 2026-08-21 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_organization_requires_identity_verification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='requires_identity_verification',
            field=models.BooleanField(default=False, help_text="Si vrai, seules les adhésions à l'identité vérifiée ouvrent l'accès (cas des universités partenaires offrant l'accès gratuit sur preuve). Mettre à faux pour une entreprise qui achète simplement des places."),
        ),
    ]
