# Generated by Django 5.2.16 on 2026-09-26 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_organization_requires_identity_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('individual', 'Individual learner'), ('teacher_author', 'Teacher/author'), ('organization_admin', 'Organization admin'), ('content_admin', 'BiblioGABON content admin'), ('platform_staff', 'Platform staff')], default='individual', max_length=32),
        ),
    ]
