# Generated by Django 5.2.16 on 2026-07-27 17:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_rightsagreement'),
        ('document_ingestion', '0003_remove_documentasset_public_url_and_more'),
        ('document_processing', '0004_alter_searchindexrecord_content_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReaderSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='active', max_length=16)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('client_ip', models.CharField(blank=True, max_length=45)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reader_sessions', to='catalog.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reader_sessions', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reader_sessions', to='document_ingestion.documentversion')),
            ],
            options={
                'ordering': ['-started_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('accessed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client_ip', models.CharField(blank=True, max_length=45)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='page_access_logs', to='catalog.document')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_logs', to='document_processing.documentpage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='page_access_logs', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_access_logs', to='document_reader.readersession')),
            ],
            options={
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='readersession',
            index=models.Index(fields=['user', 'status'], name='reader_session_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='readersession',
            index=models.Index(fields=['document', 'status'], name='reader_session_doc_status_idx'),
        ),
        migrations.AddIndex(
            model_name='readersession',
            index=models.Index(fields=['expires_at'], name='reader_session_expires_idx'),
        ),
        migrations.AddIndex(
            model_name='pageaccesslog',
            index=models.Index(fields=['user', 'accessed_at'], name='page_access_user_time_idx'),
        ),
        migrations.AddIndex(
            model_name='pageaccesslog',
            index=models.Index(fields=['document', 'accessed_at'], name='page_access_doc_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='pageaccesslog',
            constraint=models.CheckConstraint(condition=models.Q(('page_number__gte', 1)), name='page_access_log_page_number_positive'),
        ),
    ]
