"""Rend PageAccessLog.page nullable.

ATTENTION — cette migration n'est pas reversible en pratique. Des qu'une
page est supprimee (remplacement du contenu d'une version), son journal
survit avec page_id a NULL, et restaurer la contrainte NOT NULL echouerait :
il n'existe aucune donnee a y remettre.

Le journal reste exploitable sans cette cle : document, numero de page,
utilisateur et horodatage y sont denormalises, et les agregats analytics
ne traversent jamais la relation.
"""

# Generated by Django 5.2.16 on 2026-09-26 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processing', '0004_alter_searchindexrecord_content_hash'),
        ('document_reader', '0003_favoritedocument_readingprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageaccesslog',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='document_processing.documentpage'),
        ),
    ]
