"""Une ligne d'accès par page et par session.

Le tuilage IIIF a changé l'échelle du problème : afficher une page demande
des dizaines de tuiles, servies en parallèle, et chacune journalisait. Observé
comme « database is locked » sur SQLite — ce qui, sur PostgreSQL, aurait été
une tempête d'écritures concurrentes plutôt qu'une panne visible.

Les lignes antérieures peuvent violer la contrainte : elles datent d'un temps
où chaque requête en écrivait une. On garde la **première** de chaque groupe,
celle qui situe la lecture dans la fenêtre d'appartenance à l'organisation —
c'est l'horodatage dont l'agrégation se sert.
"""

# Generated by Django 5.2.16 on 2026-09-28 14:57

from django.conf import settings


def deduplicate_page_access_logs(apps, schema_editor):
    PageAccessLog = apps.get_model("document_reader", "PageAccessLog")
    seen = set()
    doomed = []
    for row in PageAccessLog.objects.order_by("accessed_at", "pk").values_list(
        "pk", "session_id", "page_id"
    ):
        primary_key, session_id, page_id = row
        if page_id is None:
            # Une page supprimée : la contrainte ne s'y applique pas, et ces
            # lignes restent la seule trace de lectures réelles.
            continue
        key = (session_id, page_id)
        if key in seen:
            doomed.append(primary_key)
        else:
            seen.add(key)
    PageAccessLog.objects.filter(pk__in=doomed).delete()


def keep_duplicates(apps, schema_editor):
    """Le retour arrière ne réinvente pas les lignes supprimées."""


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_reduce_publication_status'),
        ('document_processing', '0005_extractedtext_word_boxes'),
        ('document_reader', '0004_alter_pageaccesslog_page'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(deduplicate_page_access_logs, keep_duplicates),
        migrations.AddConstraint(
            model_name='pageaccesslog',
            constraint=models.UniqueConstraint(fields=('session', 'page'), name='page_access_log_one_row_per_session_page'),
        ),
    ]
