# Generated by Django 5.2.16 on 2026-07-27 15:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_entitlement'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=200)),
                ('normalized_name', models.CharField(max_length=220)),
                ('author_type', models.CharField(choices=[('person', 'Person'), ('group', 'Group'), ('institution', 'Institution'), ('publisher', 'Publisher'), ('other', 'Other rights holder')], default='person', max_length=24)),
                ('affiliation', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['normalized_name', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=260)),
                ('slug', models.SlugField(unique=True)),
                ('abstract', models.TextField(blank=True)),
                ('language_code', models.CharField(default='fr', max_length=12)),
                ('publication_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('category', models.CharField(choices=[('voluntary_teacher_deposit', 'Voluntary teacher deposit'), ('institutional_fund', 'Institutional fund'), ('student_work', 'Student work'), ('open_resource', 'Open resource'), ('commercial_partner_content', 'Commercial partner content')], max_length=40)),
                ('access_model', models.CharField(choices=[('free', 'Free'), ('subscription', 'Subscription'), ('institution_only', 'Institution only'), ('sponsored', 'Sponsored'), ('restricted', 'Restricted'), ('private', 'Private')], max_length=24)),
                ('publication_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('rights_review', 'Rights review'), ('technical_processing', 'Technical processing'), ('editorial_review', 'Editorial review'), ('published', 'Published'), ('withdrawn', 'Withdrawn'), ('archived', 'Archived'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='draft', max_length=32)),
                ('confidentiality_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('academic_domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='catalog.academicdomain')),
                ('owner_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_documents', to='accounts.organization')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('author', 'Author'), ('coauthor', 'Co-author'), ('supervisor', 'Supervisor'), ('editor', 'Editor'), ('institutional_contributor', 'Institutional contributor')], default='author', max_length=32)),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_authorships', to='catalog.author')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_authors', to='catalog.document')),
            ],
            options={
                'ordering': ['document', 'position'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='authors',
            field=models.ManyToManyField(related_name='documents', through='catalog.DocumentAuthor', to='catalog.author'),
        ),
        migrations.AddConstraint(
            model_name='documentauthor',
            constraint=models.UniqueConstraint(fields=('document', 'author'), name='uniq_author_per_document'),
        ),
        migrations.AddConstraint(
            model_name='documentauthor',
            constraint=models.UniqueConstraint(fields=('document', 'position'), name='uniq_author_position_per_document'),
        ),
    ]
