# Generated by Django 5.2.16 on 2026-07-27 15:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_author_document_documentauthor_document_authors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RightsAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rights_holder_name', models.CharField(max_length=240)),
                ('agreement_type', models.CharField(choices=[('teacher_voluntary', 'Teacher voluntary publication'), ('institutional_archive', 'Institutional archive/fund'), ('student_consent', 'Student work consent'), ('open_license', 'Open license'), ('commercial_distribution', 'Commercial distribution')], max_length=40)),
                ('authorization_status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revoked', 'Revoked')], default='draft', max_length=24)),
                ('authorization_date', models.DateField(blank=True, null=True)),
                ('access_model', models.CharField(choices=[('free', 'Free'), ('subscription', 'Subscription'), ('institution_only', 'Institution only'), ('sponsored', 'Sponsored'), ('restricted', 'Restricted'), ('private', 'Private')], max_length=24)),
                ('withdrawal_rule', models.CharField(choices=[('author_request', 'Author request'), ('contract_terms', 'Contract terms'), ('confidentiality_override', 'Confidentiality override'), ('license_invalid', 'License invalid'), ('commercial_terms', 'Commercial terms')], max_length=40)),
                ('revenue_sharing_rule', models.TextField(blank=True)),
                ('confidentiality_terms', models.TextField(blank=True)),
                ('consent_reference', models.CharField(blank=True, max_length=160)),
                ('reviewer_decision', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('audit_reference', models.CharField(blank=True, max_length=160)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rights_agreement', to='catalog.document')),
            ],
            options={
                'ordering': ['document__title'],
            },
        ),
    ]
