# Generated by Django 5.2.16 on 2026-07-27 21:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_entitlement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
                ('offer_type', models.CharField(choices=[('individual', 'Individual subscription'), ('organization', 'Organization access'), ('sponsored', 'Sponsored access')], max_length=24)),
                ('billing_period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('semester', 'Semester'), ('annual', 'Annual'), ('campaign', 'Campaign')], max_length=24)),
                ('price_xaf', models.IntegerField()),
                ('duration_days', models.PositiveIntegerField()),
                ('access_right', models.CharField(choices=[('read', 'Read'), ('download', 'Download'), ('offline', 'Offline')], max_length=16)),
                ('scope_type', models.CharField(choices=[('global', 'Global'), ('domain', 'Domain'), ('collection', 'Collection'), ('document', 'Document')], default='global', max_length=16)),
                ('scope_id', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('external_reference', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entitlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_subscriptions', to='accounts.entitlement')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.commercialoffer')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_subscriptions', to='accounts.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-starts_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank transfer'), ('manual_invoice', 'Manual invoice'), ('cash', 'Cash'), ('admin', 'Admin')], max_length=24)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='initiated', max_length=16)),
                ('amount_xaf', models.IntegerField()),
                ('currency', models.CharField(default='XAF', max_length=3)),
                ('idempotency_key', models.CharField(max_length=180, unique=True)),
                ('provider_reference', models.CharField(blank=True, max_length=180)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('failure_code', models.CharField(blank=True, max_length=80)),
                ('failure_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('initiated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pending_at', models.DateTimeField(blank=True, null=True)),
                ('succeeded_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_transactions', to='billing.commercialoffer')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='accounts.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='billing.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('seat_limit', models.PositiveIntegerField()),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('contract_reference', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entitlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_quotas', to='accounts.entitlement')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_quotas', to='billing.commercialoffer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_quotas', to='accounts.organization')),
            ],
            options={
                'ordering': ['organization__name', '-starts_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='billing_org_organiz_4174f1_idx'), models.Index(fields=['starts_at', 'ends_at'], name='billing_org_starts__b7867e_idx')],
            },
        ),
        migrations.CreateModel(
            name='SponsoredCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('funded_seat_count', models.PositiveIntegerField()),
                ('access_right', models.CharField(choices=[('read', 'Read'), ('download', 'Download'), ('offline', 'Offline')], max_length=16)),
                ('scope_type', models.CharField(choices=[('global', 'Global'), ('domain', 'Domain'), ('collection', 'Collection'), ('document', 'Document')], default='global', max_length=16)),
                ('scope_id', models.CharField(blank=True, max_length=128)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_campaigns', to='accounts.organization')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['status', 'starts_at', 'ends_at'], name='billing_spo_status_eca850_idx'), models.Index(fields=['sponsor', 'status'], name='billing_spo_sponsor_51eada_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'status'], name='billing_sub_user_id_fe5b98_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['organization', 'status'], name='billing_sub_organiz_e1331c_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['starts_at', 'ends_at'], name='billing_sub_starts__04c65d_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status', 'provider'], name='billing_pay_status_e504cd_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['provider_reference'], name='billing_pay_provide_b6d1db_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['created_at'], name='billing_pay_created_d70ee8_idx'),
        ),
    ]
