# Generated by Django 5.2.16 on 2026-07-28 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'base_manager_name': 'objects', 'ordering': ['-created_at']},
        ),
    ]
