# Generated by Django 5.2.16 on 2026-09-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_alter_auditlog_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='category',
            field=models.CharField(choices=[('support', 'Support request'), ('document_report', 'Document report'), ('withdrawal_request', 'Withdrawal request')], db_index=True, default='support', max_length=24),
        ),
    ]
