# Generated by Django 5.2.16 on 2026-07-28 18:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_entitlement'),
        ('catalog', '0003_rightsagreement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_type', models.CharField(choices=[('daily_usage_aggregate', 'Daily usage aggregate'), ('institution_report', 'Institution report')], max_length=32)),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='running', max_length=16)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_runs', to='accounts.organization')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['run_type', 'status'], name='analytics_run_type_status_idx'), models.Index(fields=['period_start', 'period_end'], name='analytics_run_period_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyUsageAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('access_model', models.CharField(choices=[('free', 'Free'), ('subscription', 'Subscription'), ('institution_only', 'Institution only'), ('sponsored', 'Sponsored'), ('restricted', 'Restricted'), ('private', 'Private')], max_length=24)),
                ('reader_session_count', models.PositiveIntegerField(default=0)),
                ('page_view_count', models.PositiveIntegerField(default=0)),
                ('distinct_document_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_usage_aggregates', to='catalog.academicdomain')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_usage_aggregates', to='catalog.document')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_usage_aggregates', to='accounts.organization')),
            ],
            options={
                'ordering': ['-date', 'organization__name', 'document__title'],
                'indexes': [models.Index(fields=['date', 'organization'], name='daily_usage_date_org_idx'), models.Index(fields=['document', 'date'], name='daily_usage_doc_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('date', 'organization', 'document', 'academic_domain', 'access_model'), name='uniq_daily_usage_aggregate_dim', nulls_distinct=False)],
            },
        ),
        migrations.CreateModel(
            name='InstitutionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('failed', 'Failed')], default='generated', max_length=16)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_institution_reports', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_reports', to='accounts.organization')),
            ],
            options={
                'ordering': ['organization__name', '-period_end'],
                'indexes': [models.Index(fields=['organization', 'period_start', 'period_end'], name='institution_report_period_idx'), models.Index(fields=['status', 'generated_at'], name='institution_report_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'period_start', 'period_end'), name='uniq_institution_report_period')],
            },
        ),
    ]
