# Generated by Django 5.2.16 on 2026-07-27 20:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_rightsagreement'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSearchIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=260)),
                ('slug', models.SlugField(max_length=260)),
                ('abstract', models.TextField(blank=True)),
                ('language_code', models.CharField(default='fr', max_length=12)),
                ('publication_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('access_model', models.CharField(choices=[('free', 'Free'), ('subscription', 'Subscription'), ('institution_only', 'Institution only'), ('sponsored', 'Sponsored'), ('restricted', 'Restricted'), ('private', 'Private')], max_length=24)),
                ('domain_name', models.CharField(blank=True, max_length=160)),
                ('domain_slug', models.SlugField(blank=True, max_length=160)),
                ('author_names', models.TextField(blank=True)),
                ('metadata_text', models.TextField(blank=True)),
                ('page_text', models.TextField(blank=True)),
                ('indexed_page_count', models.PositiveIntegerField(default=0)),
                ('indexed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search_index', to='catalog.document')),
            ],
            options={
                'ordering': ['title'],
                'indexes': [models.Index(fields=['domain_slug'], name='discovery_domain_slug_idx'), models.Index(fields=['language_code'], name='discovery_language_idx'), models.Index(fields=['access_model'], name='discovery_access_idx'), models.Index(fields=['publication_year'], name='discovery_year_idx')],
            },
        ),
    ]
