# Generated by Django 5.2.16 on 2026-08-21 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_documenttype_collection_collectionitem_and_more'),
        ('search_discovery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsearchindex',
            name='type_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='documentsearchindex',
            name='type_slug',
            field=models.SlugField(blank=True, default='', max_length=160),
        ),
        migrations.AddIndex(
            model_name='documentsearchindex',
            index=models.Index(fields=['type_slug'], name='discovery_type_slug_idx'),
        ),
    ]
