# Generated by Django 5.2.16 on 2026-07-27 17:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document_ingestion', '0003_remove_documentasset_public_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pages', to='document_ingestion.processingjob')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='document_ingestion.documentversion')),
            ],
            options={
                'ordering': ['version', 'page_number'],
                'constraints': [models.UniqueConstraint(fields=('version', 'page_number'), name='uniq_page_number_per_document_version'), models.CheckConstraint(condition=models.Q(('page_number__gte', 1)), name='document_page_number_positive')],
            },
        ),
    ]
