# Generated by Django 5.2.16 on 2026-07-27 17:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_ingestion', '0003_remove_documentasset_public_url_and_more'),
        ('document_processing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('language_code', models.CharField(default='fr', max_length=12)),
                ('extraction_method', models.CharField(choices=[('text_layer', 'Text layer'), ('ocr', 'OCR'), ('manual', 'Manual')], default='text_layer', max_length=24)),
                ('confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_extracted_texts', to='document_ingestion.processingjob')),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_text', to='document_processing.documentpage')),
            ],
            options={
                'ordering': ['page'],
            },
        ),
    ]
