# Generated by Django 5.2.16 on 2026-07-27 17:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processing', '0002_extractedtext'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchIndexRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('indexed', 'Indexed'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('content_hash', models.CharField(max_length=64)),
                ('language_code', models.CharField(default='fr', max_length=12)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search_index_record', to='document_processing.documentpage')),
            ],
            options={
                'ordering': ['page'],
                'indexes': [models.Index(fields=['status'], name='search_index_status_idx'), models.Index(fields=['language_code'], name='search_index_language_idx')],
            },
        ),
    ]
