# Generated by Django 5.2.16 on 2026-07-27 17:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processing', '0003_searchindexrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchindexrecord',
            name='content_hash',
            field=models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='Content hash must be a lowercase SHA-256 hex digest', regex='^[a-f0-9]{64}$')]),
        ),
    ]
