# Generated by Django 5.2.16 on 2026-09-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processing', '0004_alter_searchindexrecord_content_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedtext',
            name='word_boxes',
            field=models.JSONField(blank=True, default=list, help_text='Position de chaque mot sur la page, en fractions de la largeur et de la hauteur : [[x0, y0, x1, y1, mot], …]. Des fractions et non des pixels, pour que les positions survivent à un changement de largeur de rendu — un stockage en pixels se décalerait en silence le jour où DOCUMENT_PAGE_IMAGE_WIDTH change. Liste vide quand les positions sont inconnues : le lecteur retombe alors sur le texte à plat.'),
        ),
    ]
