# Generated by Django 5.2.16 on 2026-07-27 16:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_rightsagreement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_label', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('queued', 'Queued'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed'), ('superseded', 'Superseded')], default='uploaded', max_length=24)),
                ('is_current', models.BooleanField(default=True)),
                ('source_retention_policy', models.CharField(choices=[('retain_private_source', 'Retain private source'), ('delete_after_processing', 'Delete after processing')], default='retain_private_source', max_length=32)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('detected_format', models.CharField(blank=True, max_length=32)),
                ('processing_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='catalog.document')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_document_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['document__title', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('source_raw', 'Source raw'), ('source_pdf', 'Source PDF'), ('source_epub', 'Source EPUB'), ('page_image', 'Page image'), ('ocr_text', 'OCR text'), ('cover', 'Cover'), ('epub_package', 'EPUB package'), ('derived_file', 'Derived file')], max_length=24)),
                ('storage_bucket', models.CharField(max_length=160)),
                ('storage_key', models.CharField(max_length=500)),
                ('mime_type', models.CharField(max_length=120)),
                ('byte_size', models.PositiveBigIntegerField()),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('internal', 'Internal')], default='private', max_length=16)),
                ('public_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='document_ingestion.documentversion')),
            ],
            options={
                'ordering': ['version', 'asset_type', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(fields=('document', 'version_label'), name='uniq_version_label_per_document'),
        ),
        migrations.AddConstraint(
            model_name='documentasset',
            constraint=models.UniqueConstraint(fields=('version', 'asset_type', 'checksum_sha256'), name='uniq_asset_checksum_per_version_type'),
        ),
    ]
