# Generated by Django 5.2.16 on 2026-07-27 16:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('ingest_source', 'Ingest source'), ('extract_metadata', 'Extract metadata'), ('generate_derivatives', 'Generate derivatives'), ('ocr', 'OCR'), ('index', 'Index')], max_length=32)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('retrying', 'Retrying'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('idempotency_key', models.CharField(max_length=180, unique=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=180)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_message', models.TextField(blank=True)),
                ('input_payload', models.JSONField(blank=True, default=dict)),
                ('output_asset_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('source_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_jobs', to='document_ingestion.documentasset')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='document_ingestion.documentversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='documentasset',
            name='created_by_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assets', to='document_ingestion.processingjob'),
        ),
    ]
