# Generated by Django 5.2.16 on 2026-07-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_ingestion', '0002_processingjob_documentasset_created_by_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentasset',
            name='public_url',
        ),
        migrations.AddConstraint(
            model_name='documentasset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('storage_key__contains', '://'), _negated=True), models.Q(('storage_key__startswith', '//'), _negated=True), models.Q(('storage_key__contains', '..'), _negated=True)), name='document_asset_storage_key_not_public_scheme'),
        ),
    ]
