# Generated by Django 5.2.16 on 2026-09-26 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_ingestion', '0003_remove_documentasset_public_url_and_more'),
        ('document_processing', '0004_alter_searchindexrecord_content_hash'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='documentasset',
            name='uniq_asset_checksum_per_version_type',
        ),
        migrations.AddField(
            model_name='documentasset',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='document_processing.documentpage'),
        ),
        migrations.AddConstraint(
            model_name='documentasset',
            constraint=models.UniqueConstraint(condition=models.Q(('page__isnull', True)), fields=('version', 'asset_type', 'checksum_sha256'), name='uniq_asset_checksum_per_version_type'),
        ),
        migrations.AddConstraint(
            model_name='documentasset',
            constraint=models.UniqueConstraint(condition=models.Q(('page__isnull', False)), fields=('page', 'asset_type'), name='uniq_asset_per_page_and_type'),
        ),
    ]
